# Generated by Django 3.0.7 on 2020-12-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('Trainer', 'Trainer'), ('Member', 'Member'), ('Passager', 'Passager'), ('Conducteur', 'Conducteur')], default='Member', max_length=15),
        ),
    ]
