# Generated by Django 3.0.7 on 2020-12-12 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201212_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', help_text='example@domain.com', max_length=254)),
                ('dateNaissance', models.DateField(default=django.utils.timezone.now)),
                ('lieuNaissance', models.CharField(default='', help_text='Ex : Nioro du Rip', max_length=70)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'Passager'}, on_delete=django.db.models.deletion.CASCADE, related_name='passager_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
