# Generated by Django 3.0.7 on 2020-12-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passager'),
    ]

    operations = [
        migrations.AddField(
            model_name='passager',
            name='profile_actif',
            field=models.BooleanField(default=False),
        ),
    ]
