# Generated by Django 3.0.7 on 2020-12-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passager_profile_actif'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passager',
            new_name='PassagerProfile',
        ),
    ]
