# Generated by Django 3.0.7 on 2020-12-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useraccount_profile_actif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passagerprofile',
            old_name='profile_actif',
            new_name='email_verifie',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='profile_actif',
            new_name='email_verifie',
        ),
    ]
