# Generated by Django 3.0.7 on 2020-12-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201212_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passagerprofile',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='passagerprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='passagerprofile',
            name='fumeur',
        ),
        migrations.RemoveField(
            model_name='passagerprofile',
            name='musique',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='discussion',
            field=models.CharField(choices=[(True, "J'aime discuter parfois"), (False, "Je n'aime pas discuter quand je conduis")], default=True, max_length=15),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='experience',
            field=models.CharField(choices=[('Debutant', 'Debutant'), ('Habitue', 'Habitué'), ('Confirme', 'Confirmé'), ('Expert', 'Expert'), ('Ambassadeur', 'Ambassadeur')], default='Debutant', max_length=15),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='fumeur',
            field=models.CharField(choices=[(True, "J'accepte la fumée"), (False, "Je n'aime pas la fumée dans la voiture")], default=False, max_length=15),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='musique',
            field=models.CharField(choices=[(True, "J'aime bien écouter de la musique"), (False, "Je n'aime pas écouter de la musique en conduisant")], default=True, max_length=15),
        ),
    ]
