# Generated by Django 3.0.7 on 2020-12-16 11:58

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201215_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=200)),
                ('modele', models.CharField(max_length=200)),
                ('couleur', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('Carburant', models.CharField(choices=[('Essence', 'Essence'), ('Gazoil', 'Gazoil'), ('Electrique', 'Electrique'), ('Hybride', 'Hybride')], max_length=15)),
                ('Matricule', models.CharField(max_length=30)),
                ('proprietaire', models.OneToOneField(limit_choices_to={'role': 'Conducteur'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
