# Generated by Django 3.0.7 on 2020-12-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_vehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='Matricule',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='modele',
            field=models.CharField(default='', max_length=200),
        ),
    ]
