# Generated by Django 3.0.7 on 2020-12-16 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201216_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='proprietaire',
            field=models.OneToOneField(default='users.UserAccount', limit_choices_to={'role': 'Conducteur'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
