# Generated by Django 3.0.7 on 2020-12-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201216_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='proprietaire',
            field=models.CharField(default='users.UserAccount', max_length=150),
        ),
    ]
