# Generated by Django 3.0.7 on 2020-12-16 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20201216_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
