# Generated by Django 3.0.7 on 2020-12-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_vehicule_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='Carburant',
            new_name='carburant',
        ),
        migrations.RenameField(
            model_name='vehicule',
            old_name='Matricule',
            new_name='matricule',
        ),
    ]
