# Generated by Django 3.0.7 on 2020-12-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20201216_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicule',
        ),
    ]
