# Generated by Django 3.0.7 on 2020-12-16 14:07

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_delete_vehicule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(default='', max_length=200)),
                ('modele', models.CharField(default='', max_length=200)),
                ('couleur', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('carburant', models.CharField(choices=[('Essence', 'Essence'), ('Gazoil', 'Gazoil'), ('Electrique', 'Electrique'), ('Hybride', 'Hybride')], max_length=15)),
                ('matricule', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('proprietaire', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
