# Generated by Django 3.0.7 on 2020-12-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_departement_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='nom',
            field=models.CharField(default='', max_length=70, unique=True),
        ),
    ]
