# Generated by Django 3.0.7 on 2020-12-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20201216_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='users.Region'),
        ),
    ]
