# Generated by Django 3.0.7 on 2020-12-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20201216_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_locatite', models.BooleanField(choices=[('Region', 'Région'), ('Departement', 'Département'), ('Commune', 'Commune'), ('Village', 'Village')], default='Commune', verbose_name='Type de la localité')),
                ('nom', models.CharField(default='', max_length=70, verbose_name='Nom de la localité')),
                ('description', models.CharField(default='', max_length=200)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localites', to='users.Departement')),
            ],
            options={
                'verbose_name': 'Localite',
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_ht', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire TTC')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='users.Localite')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='users.Localite')),
                ('etapes', models.ManyToManyField(blank=True, null=True, related_name='etapes', to='users.Localite')),
            ],
        ),
    ]
