# Generated by Django 3.0.7 on 2020-12-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_localite_trajet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localite',
            name='type_locatite',
            field=models.BooleanField(choices=[('Region', 'Region'), ('Departement', 'Departement'), ('Commune', 'Commune'), ('Village', 'Village')], default='Commune', verbose_name='Type de la localité'),
        ),
    ]
