# Generated by Django 3.0.7 on 2020-12-17 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20201217_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='date_depart',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de départ'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='heure_arrivee',
            field=models.TimeField(blank=True, null=True, verbose_name='To'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True, verbose_name='From'),
        ),
    ]
