# Generated by Django 3.0.7 on 2020-12-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20201217_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='heure_arrivee',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée"),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de départ'),
        ),
    ]
