# Generated by Django 3.0.7 on 2020-12-17 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20201217_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='date_arrivee',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'arrivé"),
        ),
    ]
