# Generated by Django 3.0.7 on 2020-12-17 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20201217_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='conducteur',
        ),
        migrations.AddField(
            model_name='trajet',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
