# Generated by Django 3.0.7 on 2020-12-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20201217_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='author',
        ),
    ]
