# Generated by Django 3.0.7 on 2020-12-17 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_trajet_conducteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='maj',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='conducteur',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Conducteur'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='prix_ht',
            field=models.PositiveIntegerField(verbose_name='Prix unitaire HT'),
        ),
    ]
