# Generated by Django 3.0.7 on 2020-12-17 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20201217_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='prix_ttc',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Prix unitaire TTC'),
        ),
    ]
