# Generated by Django 3.0.7 on 2020-12-17 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20201217_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='nb_places',
            field=models.PositiveIntegerField(default=4, verbose_name='Places disponibles'),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Avis')),
                ('fait_le', models.DateTimeField(auto_now=True)),
                ('fait_par', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Avis fait par')),
                ('fait_sur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis_sur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
