# Generated by Django 3.0.7 on 2020-12-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20201217_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avis',
            options={'verbose_name': 'Avis'},
        ),
    ]
