# Generated by Django 3.0.7 on 2020-12-18 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20201217_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='fait_par',
            new_name='auteur',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='fait_sur',
        ),
        migrations.AddField(
            model_name='passagerprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passagerprofile',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Profile actif'),
        ),
        migrations.CreateModel(
            name='ConducteurProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Profile actif')),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'Conducteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='conducteur_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
