# Generated by Django 3.0.7 on 2020-12-18 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20201218_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='auteur',
        ),
        migrations.AddField(
            model_name='avis',
            name='avis_pour',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
