# Generated by Django 3.0.7 on 2020-12-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20201218_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='avis_pour',
            new_name='fait_sur',
        ),
    ]
