# Generated by Django 3.0.7 on 2020-12-18 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20201218_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trajet',
            options={'ordering': ['maj', 'date_depart'], 'verbose_name': 'Trajet'},
        ),
        migrations.AlterField(
            model_name='trajet',
            name='date_arrivee',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'arrivée"),
        ),
    ]
