# Generated by Django 3.0.7 on 2020-12-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20201218_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='trajet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='users.Trajet'),
        ),
    ]
