# Generated by Django 3.0.7 on 2020-12-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20201218_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='statue',
            field=models.CharField(choices=[('Complet', 'Complet'), ('Termine', 'Termine'), ('Annule', 'Annule'), ('Ouvert', 'Ouvert')], default='Ouvert', max_length=15),
        ),
    ]
