# Generated by Django 3.0.7 on 2020-12-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_trajet_statue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departement',
            options={'verbose_name': 'Departement'},
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together={('nom', 'region')},
        ),
    ]
