# Generated by Django 3.0.7 on 2020-12-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20201219_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='members',
            field=models.ManyToManyField(limit_choices_to={'is_disabled': True}, to='users.PassagerProfile'),
        ),
    ]
