# Generated by Django 3.0.7 on 2020-12-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_auto_20201219_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_actif',
            field=models.BooleanField(default=False, verbose_name='Profile actif'),
        ),
    ]
