# Generated by Django 3.0.7 on 2020-12-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='members',
            field=models.ManyToManyField(limit_choices_to={'is_disabled': True}, to='users.Membership'),
        ),
    ]
