# Generated by Django 3.0.7 on 2020-12-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_trajet_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='members',
            field=models.ManyToManyField(limit_choices_to={'profile_actif': True}, to='users.Membership'),
        ),
    ]
