# Generated by Django 3.0.7 on 2020-12-19 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_auto_20201219_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
