# Generated by Django 3.0.7 on 2020-12-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Description du role'),
        ),
    ]
