# Generated by Django 3.0.7 on 2020-12-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(default='', verbose_name='Description du role'),
        ),
    ]
