# Generated by Django 3.0.7 on 2020-12-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_auto_20201220_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('Trainer', 'Trainer'), ('Member', 'Member'), ('Passager', 'Passager'), ('Conducteur', 'Conducteur')], default='Passager', max_length=15),
        ),
    ]
