# Generated by Django 3.0.7 on 2020-12-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_auto_20201220_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='statue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statue', to='users.StatutTrajet'),
        ),
    ]
